### ISSUE TITLE
Handling 'backwards' selection direction in an EditContext implementation

### ISSUE THREAD

**Issue by GaurangTandon** [w3c/edit-context#81] opened 2023-12-13 10:08 UTC
Hi! I hope this is the right place to post questions about the EditContext spec. I've been playing around with it, looks great and works well! 🙂 But I have one question about it:

## **Background information**

The Selection API spec allows the selection anchorNode+anchorOffset to be positioned after the focusNode+focusOffset in the DOM. In this case, the selection direction is set to `'backwards'` (reverse of `'forwards'`). One use case for this is making a backwards selection with Shift key + ArrowLeft key.

This is documented here: https://www.w3.org/TR/selection-api/#dfn-forwards

## **EditContext implementation**

When handling selection updates from the visible DOM element, we need to update the selection for the EditContext manually. This is mentioned in the explainer.md file:

> EditContext's selection is NOT auto updated
> It will require web authors to map selection position from DOM space to EditContext's plain text space

This creates a problem when the user is extending a Selection in 'backwards' direction. To support it nicely, we need to maintain a separate state variable for the direction in our model, like so:

```js
class EditingModel {
  constructor() {
    // ...
    this.selectionDirection = 'forwards'; // extra variable to maintain direction
    // ...
  }
  
  updateSelection(selectionStart, selectionEnd) {
    if (selectionStart > selectionEnd) { // handle this here
      this.selectionDirection = 'backwards';
      [selectionStart, selectionEnd] = [selectionEnd, selectionStart];
    } else {
      this.selectionDirection = 'forwards'; // reset it
    }
    ...
  }
  
  render() {
    ...
    // readjust the coordinates when rendering back to DOM space
    const start = this.selectionDirection === 'forwards' ? this.selectionStart : this.selectionEnd;
    const end = this.selectionDirection === 'forwards' ? this.selectionEnd : this.selectionStart;
    window.getSelection().setBaseAndExtent(
        this.hostElement.firstChild, start,
        this.hostElement.firstChild, end);
    ...
  }
}

document.addEventListener('selectionchange', () => {
  const selectionStart = ..., // get from DOM Selection/Range APIs
    selectionEnd = ...; // this will be smaller
  
  editingModel.updateSelection(selectionStart, selectionEnd);
});
```

It seems to me that almost every editor implementing EditContext would need to handle the selection direction, which seems an extra overhead and creates potential for mistakes. For example: Shift+ArrowLeft doesn't work in one of the example apps: https://magic-organic-yam.glitch.me/ because it doesn't maintain the selection direction after the re-render (though I am aware the demo doesn't support all DOM operations)

## Question

Right now, the spec enforces the `<=` constraint in `updateSelection`:

> 2. If start > end, abort these steps.

Can backwards selection be supported in the EditContext spec? Then it would reduce the extra overhead. It looks like this would be a backwards-compatible change with the existing EditContext implementation.

**Comment by dandclark** [comment] 2023-12-16 00:51
Thanks @GaurangTandon for raising the issue! I'm inclined to agree that EditContext should allow backwards selection. Seems like it will be a continuous source of annoyance if we push it to developers to deal with this.

We ran out of time to get to it in the WG meeting this week, but I'll bring it for discussion at the next opportunity.

**Comment by dandclark** [comment] 2024-01-11 23:42
We resolved in today's Editing WG call to remove the restriction on backwards selection.

> [08:54] <whsieh> johanneswilm: moving on to https://github.com/w3c/edit-context/issues/81
[08:55] <whsieh> dandclark: it's annoying that authors need to track selection directionality in order to implement correct selection behaviors
[08:55] <whsieh> johanneswilm: resolution: allow backwards selection

**Comment by captainbrosset** [comment] 2024-02-01 10:17
@dandclark shouldn't `updateText` also allow backward selection then? E.g. `updateText(a, b, "hello")` shouldn't throw if `a > b`, since those values could come from `EditContext.selectionStart` and `EditContext.selectionEnd` directly.

**Comment by dandclark** [comment] 2024-02-02 00:14
@captainbrosset You're right! I think the spec actually allows this: https://w3c.github.io/edit-context/#dfn-selection-bounds:~:text=Replace%20the%20substring%20of%20text%20in%20the%20range%20of%20rangeStart%20and%20rangeEnd%20with%20newText; at least, it doesn't say you *can't* submit a backwards range to updateText. But perhaps a non-normative note clarifying this is a good idea.

**Comment by dandclark** [comment] 2024-02-02 00:14
The Chomium implementation still needs to be updated to allow it for updateText, though.

**Comment by dandclark** [comment] 2024-02-13 22:51
> [17:14] <smaug> topic: https://github.com/w3c/edit-context/issues/81
[17:14] * github-bot Because I don't want to spam github issues unnecessarily, I won't comment in that github issue unless you write "Github: <issue-url> | none" (or "Github issue: ..."/"Github topic: ...").
[17:14] * github-bot Successfully commented on https://github.com/w3c/edit-context/issues/89
[17:15] <smaug> dandclark: we should allow backwards selection
[17:15] <smaug> smaug: sounds good

The notes are terse, but the WG discussed this last week and confirmed that "backwards" input parameters for updateText is also the correct behavior.

**Closed as completed** 2024-02-14 00:18 UTC
Labels: needs-spec-edits

**Comment by marijnh** [comment] 2024-06-12 19:47
> The Chomium implementation still needs to be updated to allow it for updateText, though.

This still seems to be the case. Is this task tracked anywhere? I couldn't find any reference to it in the Chromium bug tracker.

**Comment by dandclark** [comment] 2024-06-13 00:13
@marijnh This was fixed [here](https://chromium-review.googlesource.com/c/chromium/src/+/5301307), and as far as I can tell is working as expected. E.g. in https://codepen.io/daniec/pen/rNgYeKP, tested in Chrome `126.0.6478.57`, updateText allows "backwards" rangeStart/rangeEnd.

Can you share an example of where you're not seeing this not work correctly?

**Comment by marijnh** [comment] 2024-06-13 05:32
> Can you share an example of where you're not seeing this not work correctly?

I was testing with 125. Great to hear it's fixed in later versions.
